language: node_js
sudo: true
node_js:
  - '10'
install:
  - npm i -g yarn
dd:
  secure: K7PikcxxeKBQUm1FDGdZI40cEZIF5aqqLGOoCxt3mcouf3vcRG6dkwxpZ6sl76/DVE03l7lEpI0pccnE2ixec1nURgeV9uNPNhsoPyu1o00b6yGBx2kQs9YbjE4h7UYAfDwbvOSMZ0kp4P+D67axbYqVuKEuXppggI9k+EmDr5XyuuIW53ETCuToXUA/ElIK9QZ7eIn7+lAffH4RtAk7vgmpanyLUQCauGrKOaHGvXe6RNvcFFQXZtbKQ/h7pE16GMVuXHkOFVKPPfI+VEDA5F8qAnUMbMMT8tsMfFQVj3nVULQyQRrQAMDPfnqSXcNWs8rKJ1nHub9TSB04Yxg/nstJRX++qirijLNZvPyAaz91C12W+evaogKmetReXv7BQiHYZS4ROiyLOtftn98vWi/rDgVor5wzX9pzXNyDeixhNjtwYJndG8RDgqEqDTotO6+d/TE79Z5WQvObttnYrfTy6fsvHVw7mXtpPbpNkAlL6ZKBagWlwX243j9qIevX+UBfDTHz+nqcignXoTcFCwpLEZ9R9//oD69N9Uw4pxR02LtU7x/I89ntG8Hr/FLwhbwkX9mbCfztmtYvzGDq1ocQcwEOY41XvFk6LR78WMb0uKFrOC7ywJGuXkeIUEmTlPhJRVunft8QBz3w6xVrdThhIucKZlgYDoWaLrdwNK8=
deploy:
  provider: npm
  email: jonathan.glanz@gmail.com
  api_key:
    secure: q0YZXYFx+/tvfbRRU4Mg2EZGwZM3hzwRc6RjRZaw6NLTtgH5/b0Oys8fVvmJWFcThlOwFDzpVelVOkY+5zhWm0B3mIdtiO6Qw6M4IcfbftgYCn4dWnK0wmIZXzs8fEvWQYBkDlqt/XktTHl5Wg1IwAroBf6ctvt+pIjxTGOsld4AMZnw7GghQgRLMngiRwRW6Zqqsx8gDVXlnPuKDg82ryAhyjlO13gKcT6z7R1w9S9fmoHlzLTJ31ob47ePxOqm7ZQe52Wt3zm2LoCQyntyCABCvnGkLz7bmpSN6HE1G1ABcAN/hz4UMvrjn9KFHZdAXQPCA7rylJvVxRUZtdb98koBoJ7H/gQ1mTfQSpczVqbX1I4vneKDF8OYWtHIHwUXLbTq8z2BL+GUz5yCg1TAo5W8REQVC4oR735yBcjytsz7yXqVEtjO790gas/hfjv6tA94EktmUherrdeKf6Y2QLuD+LRAjA+3BezwYeMiq/up4Sa/P9CVnjsCxjWTaYr8ssdXPo8pwEXzP5tt2/0RluBzyE/5T341oGdc729IUDwkZfYXdZj+16uVA4wPs81J4d+R85VlEogj1lOjWwzxGVDyrU6/HvuZ1h23w8Ux9nK14Pl4X6i4rBPzf5fvocTB+6/geUnY9jYhA6NZzsQIM8Z0gmIOue9xO4PV8ssei7U=
  on:
    branch: master
    tags: true
